//! Ingest: local video file → bundle skeleton with a truthful manifest.
//!
//! Fixtures are tiny videos generated by ffmpeg at test time; the expected
//! values (duration, resolution, audio) are the generation parameters —
//! an independent source of truth from the probing implementation.

// Integration-test file: everything here is test code, where unwrap is fine.
#![allow(clippy::unwrap_used)]

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use vts_extract::bundle::{ingest, load_manifest};
use vts_extract::tools::Toolchain;

fn scratch(name: &str) -> PathBuf {
    let dir = std::env::temp_dir()
        .join("vts-ingest-tests")
        .join(format!("{name}-{}", std::process::id()));
    if dir.exists() {
        fs::remove_dir_all(&dir).unwrap();
    }
    fs::create_dir_all(&dir).unwrap();
    dir
}

fn toolchain() -> Toolchain {
    // Tests rely on ffmpeg/ffprobe from PATH (CI installs them).
    Toolchain {
        ffmpeg: PathBuf::from("ffmpeg"),
        ffprobe: PathBuf::from("ffprobe"),
        whisper_model: None,
    }
}

/// 2-second 320x240 10fps test pattern, optionally with a sine audio track.
fn generate_video(dir: &Path, container: &str, audio: bool) -> PathBuf {
    let out = dir.join(format!("fixture.{container}"));
    let (vcodec, acodec) = match container {
        "webm" => ("libvpx", "libvorbis"),
        _ => ("mpeg4", "aac"),
    };
    let mut cmd = Command::new("ffmpeg");
    cmd.args([
        "-y",
        "-f",
        "lavfi",
        "-i",
        "testsrc=duration=2:size=320x240:rate=10",
    ]);
    if audio {
        cmd.args(["-f", "lavfi", "-i", "sine=frequency=440:duration=2"]);
    }
    cmd.args(["-c:v", vcodec]);
    if audio {
        cmd.args(["-c:a", acodec, "-shortest"]);
    }
    cmd.arg(&out);
    let status = cmd.output().unwrap();
    assert!(
        status.status.success(),
        "fixture generation failed: {}",
        String::from_utf8_lossy(&status.stderr)
    );
    out
}

#[test]
fn manifest_matches_the_fixtures_generation_parameters() {
    let dir = scratch("mp4-audio");
    let video = generate_video(&dir, "mp4", true);
    let out = dir.join("bundle");

    let report = ingest(&video, &out, &toolchain()).unwrap();

    let m = &report.manifest;
    assert_eq!(m.schema_version, 1);
    assert!(
        (1.8..=2.3).contains(&m.media.duration_secs),
        "{}",
        m.media.duration_secs
    );
    assert_eq!((m.media.width, m.media.height), (320, 240));
    assert!((m.media.fps - 10.0).abs() < 0.1);
    assert!(m.media.has_audio);
    assert_eq!(m.media.container, "mp4");
    assert_eq!(m.source.sha256.len(), 64);
    // The manifest on disk is the same one returned.
    let reloaded = load_manifest(&out).unwrap();
    assert_eq!(reloaded, *m);
}

#[test]
fn every_supported_container_ingests() {
    for container in ["mp4", "mkv", "webm", "mov"] {
        let dir = scratch(&format!("fmt-{container}"));
        let video = generate_video(&dir, container, false);

        let report = ingest(&video, &dir.join("bundle"), &toolchain()).unwrap();

        assert_eq!(
            (report.manifest.media.width, report.manifest.media.height),
            (320, 240),
            "{container}"
        );
        assert_eq!(report.manifest.media.container, container);
    }
}

#[test]
fn video_without_audio_track_reports_no_audio() {
    let dir = scratch("silent");
    let video = generate_video(&dir, "mp4", false);

    let report = ingest(&video, &dir.join("bundle"), &toolchain()).unwrap();

    assert!(!report.manifest.media.has_audio);
}

#[test]
fn missing_file_unsupported_format_and_corrupt_file_have_distinct_errors() {
    let dir = scratch("errors");
    let tc = toolchain();

    let missing = ingest(&dir.join("nope.mp4"), &dir.join("b1"), &tc).unwrap_err();
    assert!(missing.to_string().contains("not found"), "got: {missing}");

    let text = dir.join("notes.txt");
    fs::write(&text, "just text").unwrap();
    let unsupported = ingest(&text, &dir.join("b2"), &tc).unwrap_err();
    assert!(
        unsupported.to_string().contains("Unsupported"),
        "got: {unsupported}"
    );

    let corrupt = dir.join("broken.mp4");
    fs::write(&corrupt, b"this is not an mp4 at all").unwrap();
    let unreadable = ingest(&corrupt, &dir.join("b3"), &tc).unwrap_err();
    assert!(
        unreadable.to_string().contains("corrupt"),
        "got: {unreadable}"
    );
}

#[test]
fn reingesting_the_same_source_is_idempotent() {
    let dir = scratch("idempotent");
    let video = generate_video(&dir, "mp4", false);
    let out = dir.join("bundle");
    let tc = toolchain();

    let first = ingest(&video, &out, &tc).unwrap();
    assert!(first.created);
    let second = ingest(&video, &out, &tc).unwrap();
    assert!(!second.created, "second run must reuse the bundle");
    assert_eq!(first.manifest, second.manifest);
}

#[test]
fn a_bundle_refuses_a_different_source() {
    let dir = scratch("conflict");
    let video_a = generate_video(&dir, "mp4", false);
    let video_b = generate_video(&dir, "mkv", false);
    let out = dir.join("bundle");
    let tc = toolchain();

    ingest(&video_a, &out, &tc).unwrap();
    let err = ingest(&video_b, &out, &tc).unwrap_err();

    assert!(err.to_string().contains("different"), "got: {err}");
}
