//! Pure markdown rendering of a [`BenchReport`]: the full results table
//! for `BENCHMARK.md` and the short summary for `README.md`.

use std::fmt::Write as _;

use super::{BenchReport, BenchResult};

pub const RESULTS_BEGIN: &str = "<!-- bench-results:start -->";
pub const RESULTS_END: &str = "<!-- bench-results:end -->";
pub const SUMMARY_BEGIN: &str = "<!-- bench-summary:start -->";
pub const SUMMARY_END: &str = "<!-- bench-summary:end -->";

/// Full results table + machine line + generated-at note. The date is a
/// caller-supplied string so this stays a pure function.
#[must_use]
pub fn render_results_markdown(report: &BenchReport, generated_on: &str) -> String {
    let mut out = String::from("| id | label | wall (s) | realtime | stages |\n");
    out.push_str("| --- | --- | --- | --- | --- |\n");
    for result in &report.results {
        // Writing into a String cannot fail.
        let _ = writeln!(
            out,
            "| {} | {} | {:.1} | {} | {} |",
            result.id,
            result.label,
            result.wall_secs,
            realtime_cell(result),
            stages_cell(result)
        );
    }
    let _ = writeln!(
        out,
        "\nMachine: {} · {} logical cores · {} · vts-extract {}",
        report.machine.chip, report.machine.logical_cores, report.machine.os, report.version
    );
    let _ = writeln!(
        out,
        "\n_Generated by `vts-extract bench` on {generated_on}._"
    );
    out
}

/// The 2–4 line summary spliced into `README.md`: end-to-end extract,
/// transcription realtime factor, the machine, and a link to the full
/// results.
#[must_use]
pub fn render_readme_summary(report: &BenchReport) -> String {
    let end_to_end = report
        .results
        .iter()
        .find(|r| r.id == "extract-120s")
        .map_or_else(
            || "n/a".to_string(),
            |r| {
                let realtime = r
                    .realtime_factor
                    .map(|f| format!(" · {f:.1}x realtime"))
                    .unwrap_or_default();
                format!("{:.1}s wall{realtime}", r.wall_secs)
            },
        );
    let transcription = report
        .results
        .iter()
        .find(|r| r.id == "asr-45s")
        .and_then(|r| r.realtime_factor)
        .map_or_else(|| "n/a".to_string(), |f| format!("{f:.1}x realtime"));
    format!(
        "| 2-min 720p extract | transcription | measured on |\n\
         | --- | --- | --- |\n\
         | {end_to_end} | {transcription} | {} ({} cores) |\n\
         \n\
         Full methodology and results: [BENCHMARK.md](BENCHMARK.md)\n",
        report.machine.chip, report.machine.logical_cores
    )
}

fn realtime_cell(result: &BenchResult) -> String {
    result
        .realtime_factor
        .map_or_else(|| "—".to_string(), |f| format!("{f:.1}x"))
}

fn stages_cell(result: &BenchResult) -> String {
    if result.stages.is_empty() {
        return "—".to_string();
    }
    result
        .stages
        .iter()
        .map(|(name, secs)| format!("{name} {secs:.1}s"))
        .collect::<Vec<_>>()
        .join(" · ")
}

#[cfg(test)]
mod tests {
    use super::{render_readme_summary, render_results_markdown};
    use crate::bench::{BenchReport, BenchResult, Machine};

    fn result(
        id: &str,
        label: &str,
        wall: f64,
        media: Option<f64>,
        rt: Option<f64>,
    ) -> BenchResult {
        BenchResult {
            id: id.into(),
            label: label.into(),
            wall_secs: wall,
            media_secs: media,
            realtime_factor: rt,
            stages: Vec::new(),
        }
    }

    fn fixture_report() -> BenchReport {
        let mut extract = result(
            "extract-120s",
            "Full extract of a 120s 720p video",
            60.04,
            Some(120.0),
            Some(2.0),
        );
        extract.stages = vec![
            ("ingest".into(), 0.42),
            ("transcribe".into(), 41.9),
            ("frames".into(), 17.26),
            ("timeline".into(), 0.07),
        ];
        BenchReport {
            schema_version: 1,
            machine: Machine {
                chip: "Apple M2 Pro".into(),
                logical_cores: 12,
                os: "macos/aarch64".into(),
            },
            version: "0.2.1".into(),
            results: vec![
                result(
                    "asr-45s",
                    "Transcribe ~45s of generated speech",
                    12.34,
                    Some(45.6),
                    Some(3.7),
                ),
                extract,
                result(
                    "frames-batch-5",
                    "Batch export of 5 frames",
                    1.34,
                    None,
                    None,
                ),
            ],
        }
    }

    #[test]
    fn results_markdown_is_stable_for_a_known_report() {
        let markdown = render_results_markdown(&fixture_report(), "2026-08-05");

        assert_eq!(
            markdown,
            "| id | label | wall (s) | realtime | stages |\n\
             | --- | --- | --- | --- | --- |\n\
             | asr-45s | Transcribe ~45s of generated speech | 12.3 | 3.7x | — |\n\
             | extract-120s | Full extract of a 120s 720p video | 60.0 | 2.0x | \
             ingest 0.4s · transcribe 41.9s · frames 17.3s · timeline 0.1s |\n\
             | frames-batch-5 | Batch export of 5 frames | 1.3 | — | — |\n\
             \n\
             Machine: Apple M2 Pro · 12 logical cores · macos/aarch64 · vts-extract 0.2.1\n\
             \n\
             _Generated by `vts-extract bench` on 2026-08-05._\n"
        );
    }

    #[test]
    fn readme_summary_is_stable_for_a_known_report() {
        let summary = render_readme_summary(&fixture_report());

        assert_eq!(
            summary,
            "| 2-min 720p extract | transcription | measured on |\n\
             | --- | --- | --- |\n\
             | 60.0s wall · 2.0x realtime | 3.7x realtime | Apple M2 Pro (12 cores) |\n\
             \n\
             Full methodology and results: [BENCHMARK.md](BENCHMARK.md)\n"
        );
    }

    #[test]
    fn readme_summary_reports_na_when_the_asr_bench_was_skipped() {
        let mut report = fixture_report();
        report.results.retain(|r| r.id != "asr-45s");

        let summary = render_readme_summary(&report);

        assert!(summary.contains("| 60.0s wall · 2.0x realtime | n/a |"));
    }
}
